# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5i6-gaVk9OSsuNPgXy0_udotyX5sd2A
"""

import pandas as pd

def data_shape(filename):
    df = pd.read_csv(filename)
    return df.shape