# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUdCyWMBS86T9-LsqLKM8bE78rV1dgxp
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score

def hotel_booking_analyze(X, Y):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

    lr = LogisticRegression(max_iter=1000)
    lr.fit(X_train, Y_train)
    y_lr_pred = lr.predict(X_test)
    recall_lr = recall_score(Y_test, y_lr_pred)

    svc = SVC()
    svc.fit(X_train, Y_train)
    y_svc_pred = svc.predict(X_test)
    recall_svc = recall_score(Y_test, y_svc_pred)

    rf = RandomForestClassifier(random_state=42)
    rf.fit(X_train, Y_train)
    y_rf_pred = rf.predict(X_test)
    recall_rf = recall_score(Y_test, y_rf_pred)

    result = f"LogisticRegression: {recall_lr}. SVC: {recall_svc}. RandomForestClassifier: {recall_rf}."
    return result