# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUdCyWMBS86T9-LsqLKM8bE78rV1dgxp
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

def table_preprocessing(csv_name):
    df = pd.read_csv(csv_name)
    df = df.drop('Booking_ID', axis=1)

    le = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = le.fit_transform(df[col])
    X = df.drop('booking_status', axis=1)
    Y = df['booking_status']

    return X, Y