# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5i6-gaVk9OSsuNPgXy0_udotyX5sd2A
"""

import pandas as pd

def row_col_num(filename):
    df = pd.read_csv(filename)
    rows, cols = df.shape
    return f'В таблице {rows} строк и {cols} столбцов'