# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2gkUe1yuoKQN8JECY-zCfriqn7oC-iv
"""

import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

def website_analyse(file_path):
    df = pd.read_csv(file_path)

    mean_pages = df["Просмотренные страницы"].mean()
    std_time = df["Время на сайте (сек)"].std()

    cv = std_time / df["Время на сайте (сек)"].mean()

    if cv > 0.25:
        variability = "Высокая вариабельность"
    elif 0.1 < cv <= 0.25:
        variability = "Умеренная вариабельность"
    else:
        variability = "Слабая вариабельность"

    mobile_pages = df[df["Тип устройства"] == "Мобильное"]["Просмотренные страницы"]
    desktop_pages = df[df["Тип устройства"] == "Десктоп"]["Просмотренные страницы"]

    _, p_value = ttest_ind(mobile_pages, desktop_pages, equal_var=False)

    if p_value > 0.05:
        diff_result = "Есть статистически значимая разница в количестве страниц"
    else:
        diff_result = "Нет статистически значимой разницы"

    print(f"1) Среднее количество просмотренных таблиц: {mean_pages}")
    print(f"2) Стандартное отклонение: {std_time}")
    print(f"3) {variability}: {cv}")
    print(f"4) {diff_result}: {p_value}")